version: "3.4"

services:
  bot:
    # personal docker registry, you need to docker-login to access.
    image: registry.23alice.duckdns.org/bot:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
      network: host